services:
  postgres:
    image: postgres:15.3-alpine
    secrets:
      - postgres_password
      - postgres_user
      - postgres_db
    environment:
      POSTGRES_USER_FILE: /run/secrets/postgres_user
      POSTGRES_PASSWORD_FILE: /run/secrets/postgres_password
      POSTGRES_DB_FILE: /run/secrets/postgres_db
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - shared_network
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure

  redis:
    image: redis:7.2-alpine
    secrets:
      - redis_password
    command: >
      sh -c "redis-server
        --requirepass $$(cat /run/secrets/redis_password)
        --appendonly yes"
    volumes:
      - redis-data:/data
    networks:
      - shared_network
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure

  financial-system:
    image: teste-image
    networks:
      - shared_network
    secrets:
      - postgres_user
      - postgres_password
      - postgres_db
      - redis_password
      - access_token_secret
      - refresh_token_secret
      - token_algorithm
    environment:
      NODE_ENV: production
      PORT: 8755
      POSTGRES_HOST: postgres
      POSTGRES_PORT: 5432
      REDIS_HOST: redis
      REDIS_PORT: 6379
    ports:
      - target: 8755
        published: 8755
        protocol: tcp
        mode: ingress
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure

volumes:
  pgdata:
  redis-data:

secrets:
  postgres_password:
    external: true
  postgres_user:
    external: true
  postgres_db:
    external: true
  redis_password:
    external: true
  access_token_secret:
    external: true
  refresh_token_secret:
    external: true
  token_algorithm:
    external: true

networks:
  shared_network:
    driver: overlay