services:
  postgres:
    image: postgres:15.3-alpine   
    secrets:
      - postgres_password
      - postgres_user
      - postgres_db 
    environment:
      POSTGRES_USER_FILE: /run/secrets/postgres_user
      POSTGRES_PASSWORD_FILE: /run/secrets/postgres_password
      POSTGRES_DB_FILE: /run/secrets/postgres_db    
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - shared_network
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.role == manager
      restart_policy:
        condition: on-failure
      update_config:
        order: stop-first
      rollback_config:
        order: stop-first

  redis:
    image: redis:7.2-alpine   
    secrets:
      - redis_password
    command: >
      sh -c "redis-server
        --requirepass $$(cat /run/secrets/redis_password)
        --maxmemory 1gb
        --maxmemory-policy noeviction
        --appendonly yes
        --appendfsync everysec"  
    volumes:
      - redis-data:/data
    networks:
      - shared_network
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
      update_config:
        order: stop-first
      rollback_config:
        order: stop-first

  financial-system:
    image: teste-image
    networks:
      - shared_network
    secrets:
      - postgres_user
      - postgres_password
      - postgres_db
    ports:
      - target: 8755
        published: 8755
        protocol: tcp
        mode: ingress
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
      update_config:
        order: start-first
        failure_action: rollback
      rollback_config:
        order: stop-first

volumes:
  pgdata:
  redis-data:

secrets:
  postgres_password:
    external: true
  postgres_user:
    external: true
  postgres_db:
    external: true
  redis_password:
    external: true
    
networks:
  shared_network:
    driver: overlay
