apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: financial-postgres
spec:
  replicas: 1
  selector:
    matchLabels:
      app: financial-postgres
  template:
    metadata:
      labels:
        app: financial-postgres
    spec:
      containers:
        - name: financial-postgres
          image: postgres:15.3-alpine
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: password
            - name: POSTGRES_USER
              value: "postgres"
          volumeMounts:
            - name: postgres-storage
              mountPath: /var/lib/postgresql/data
      volumes:
        - name: postgres-storage
          persistentVolumeClaim:
            claimName: postgres-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: financial-postgres-service
spec:
  type: ClusterIP
  selector:
    app: financial-postgres
  ports:
    - port: 5432
      targetPort: 5432
